# Generated by Django 6.0.6 on 2026-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreentry',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='category',
            field=models.CharField(choices=[('ones', 'Einsen'), ('twos', 'Zweien'), ('threes', 'Dreien'), ('fours', 'Vieren'), ('fives', 'Fünfen'), ('sixes', 'Sechsen'), ('bonus', 'Bonus'), ('three_of_a_kind', 'Dreierpasch'), ('four_of_a_kind', 'Viererpasch'), ('full_house', 'Full House'), ('small_straight', 'Kleine Straße'), ('large_straight', 'Große Straße'), ('yahtzee', 'Kniffel'), ('chance', 'Chance')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='scoreentry',
            unique_together={('game_player', 'category')},
        ),
    ]
