# Generated by Django 6.0.6 on 2026-07-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_scoreentry_value_alter_scoreentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreentry',
            name='state',
            field=models.CharField(choices=[('empty', 'Leer'), ('filled', 'Belegt'), ('stricken', 'Gestrichen')], default='empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='category',
            field=models.CharField(choices=[('ones', 'Einsen'), ('twos', 'Zweien'), ('threes', 'Dreien'), ('fours', 'Vieren'), ('fives', 'Fünfen'), ('sixes', 'Sechsen'), ('three_of_a_kind', 'Dreierpasch'), ('four_of_a_kind', 'Viererpasch'), ('full_house', 'Full House'), ('small_straight', 'Kleine Straße'), ('large_straight', 'Große Straße'), ('yahtzee', 'Kniffel'), ('chance', 'Chance')], max_length=30),
        ),
    ]
